core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from core.views import *

urlpatterns = [

    # Custom admin urls
    path('su/monitor/admin/', comments_admin, name='comments_admin'),

    # Site urls
    path('', index, name='index'),
    path('account/profile/', user_profile, name='user_profile'),
    path('account/anonymous/', set_anonymous, name='set_anonymous'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('truecaller/login', truecaller_login, name='truecaller_login'),
    path('truecaller/auth', truecaller_auth, name='truecaller_auth'),
    path('mentors/', list_mentor, name='list_mentor'),
    path('mentor/<uuid:mentor_id>/', mentor_detail, name='mentor_detail'),
    path('message/respond/<uuid:message_id>/', message_response, name='message_response'),
    path('posts/', list_post, name='list_post'),
    path('posts/<uuid:post_id>/', post_detail, name='post_detail'),
    path('posts/create/', create_post, name='create_post'),
    path('posts/content/add/<uuid:post_id>/<str:ct>/', add_post_content, name='add_post_content'),
    path('posts/rate/', rate_post, name='rate_post'),
    path('mentor/follow/', follow_unfollow_mentor, name='follow_mentor'),
    path('mentor/like/', like_unlike_mentor, name='like_mentor'),
    path('streams/', live_stream, name='live_stream'),
    path('stream/message/respond/<uuid:message_id>/', stream_message_response, name='stream_message_response'),
    path('terms/', terms, name='terms'),
    path('privacy/', privacy, name='privacy'),

]

gyaanstation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from ckeditor_uploader import views as uploder_views
from core.decorators import uploader_decorator

urlpatterns = [
    path('', include(('core.urls', 'core'), namespace='core')),
    path('admin/', admin.site.urls),
    path('ckeditor/upload/', uploader_decorator(uploder_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', uploader_decorator(uploder_views.browse), name='ckeditor_browse'),
    path('oauth/', include(('social_django.urls', 'social'), namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms

from django.contrib.auth.models import User
from django.core.files import File

from core.models import (
    PostComment,
    Message,
    Response,
    Mentee,
    StreamMessage,
    StreamMsgResponse,
    Post,
    Text,
    Audio,
    Video,
    Link
)

from PIL import Image

class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ('resp_content',)

    def __init__(self, *args, **kwargs):
        super(ResponseForm, self).__init__(*args, **kwargs)
        self.fields['resp_content'].required = True

class StreamMessageForm(forms.ModelForm):
    class Meta:
        model = StreamMessage
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(StreamMessageForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class StreamMsgResponseForm(forms.ModelForm):
    class Meta:
        model = StreamMsgResponse
        fields = ('resp_content',)

    def __init__(self, *args, **kwargs):
        super(StreamMsgResponseForm, self).__init__(*args, **kwargs)
        self.fields['resp_content'].required = True

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

class MenteeForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Mentee
        fields = ('profile_pic', 'gender', 'phone_no', 'x', 'y', 'width', 'height')

    def save(self, *args, **kwargs):
        mentee = super(MenteeForm, self).save(*args, **kwargs)

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        try:
            image = Image.open(mentee.profile_pic)
            cropped_image = image.crop((x, y, w+x, h+y))
            cropped_image.save(mentee.profile_pic.path)
        except:
            pass
        return mentee

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'description')

class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ('thumbnail',)

class AudioForm(forms.ModelForm):
    class Meta:
        model = Audio
        fields = ('thumbnail', 'audio_file')

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('video_url',)

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('content_url',)

core/views.py
import json, requests

from itertools import chain
from operator import attrgetter

from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.csrf import (
    csrf_exempt,
    ensure_csrf_cookie
)
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.humanize.templatetags.humanize import intcomma
from django.contrib.contenttypes.models import ContentType

from django.http.response import (
    HttpResponse,
    JsonResponse
)
from django.contrib.auth import (
    login,
    authenticate
)

from django.conf import settings
from django.utils import timezone
from django.contrib import messages
from django.http import Http404

from django.db.models import Count, Avg
from django.db.models.functions import Coalesce

from django.contrib.auth.models import User

from core.models import *
from core.forms import *
from core.decorators import (
    ajax_required,
    mentee_required
)

# Custom Admin views here.

@staff_member_required
@require_http_methods(['GET'])
def comments_admin(request):
    comments = PostComment.objects.filter(approved=False).distinct()
    messages = Message.objects.filter(approved=False).distinct()
    responses =  Response.objects.filter(approved=False).distinct()
    monitor_objs = sorted(chain(comments, messages, responses), key=attrgetter('created'), reverse=True)
    return render(request, 'su/monitor.html', {'objs' : monitor_objs, 'section' : 'su_comments_admin'})

# Create your views here.

@ensure_csrf_cookie
def index(request):
    t_mentors = Mentor.objects.all().prefetch_related('likes').annotate(num_likes=Count('likes')).order_by('-num_likes')[:6]
    t_posts = Post.objects.all().annotate(avg_rating=Coalesce(Avg('ratings__value'), 0.0)).order_by('-avg_rating')[:20]
    return render(request, 'home/index.html', {'mentors' : t_mentors, 'posts' : t_posts, 'section' : 'index'})

@login_required
@require_http_methods(['GET', 'POST'])
def user_profile(request):
    if request.method == 'POST':
        u_form = UserForm(data=request.POST, instance=request.user)
        m_form = MenteeForm(data=request.POST, files=request.FILES, instance=request.user.mentee)
        if u_form.is_valid() and m_form.is_valid():
            user = u_form.save(commit=False)
            user.save()
            mentee = m_form.save()
            messages.success(request, 'Profile created successfully')
            return redirect('core:user_profile')
    else:
        u_form = UserForm(instance=request.user)
        if hasattr(request.user, 'mentee'):
            m_form = MenteeForm(instance=request.user.mentee)
        else:
            m_form = MenteeForm()
    try:
        dp_pic = request.user.mentee.profile_pic.url
    except:
        dp_pic = None
    anonymous = False
    if hasattr(request.user, 'mentee'):
        anonymous = request.user.mentee.anonymous
    return render(request, 'home/account/profile.html', {'pic' : dp_pic, 'u_form' : u_form, 'm_form' : m_form, 'anonymous' : anonymous, 'section' : 'profile'})

@mentee_required
@ajax_required
@require_http_methods(['POST'])
def set_anonymous(request):
    state = request.POST.get('state')
    if state == 'on':
        new_user_name = request.POST.get('username')
        user = request.user
        try:
            user.username = new_user_name
            user.save()
            mentee = user.mentee
            mentee.anonymous = True
            mentee.save()
        except:
            return JsonResponse({'status' : 'failed'})
    else:
        mentee = request.user.mentee
        mentee.anonymous = False
        mentee.save()
    return JsonResponse({'status' : 'success', 'state' : state})

@ajax_required
@require_http_methods(['POST'])
def truecaller_login(request):
    phone_num = '91{}'.format(request.POST.get('phone_number'))
    try:
        truecaller, created = Truecaller.objects.get_or_create(phone_number=phone_num)
    except Exception as e:
        return JsonResponse({'status' : 'Error', 'mesage' : str(e)})
    if created or timezone.now() >= truecaller.expires_at:
        url = 'https://api4.truecaller.com/v1/apps/requests'
        headers = {'content-type' : 'application/json', 'appKey' : settings.TRUECALLER_APP_KEY}
        data = {'phoneNumber' : phone_num}
        resp = requests.post(url, headers=headers, data=json.dumps(data))
        truecaller.expires_at = timezone.now() + timedelta(minutes=5)
        truecaller.save()
        if resp.ok:
            json_data = json.loads(resp.text)
            truecaller.request_id = json_data['requestId']
            truecaller.save()
            return JsonResponse({'status' : 'Waiting'})
    else:
        user = authenticate(request=request, phone_number=phone_num)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login Successful!')
            return JsonResponse({'status' : 'Success'})
    return JsonResponse({'status' : 'Waiting'})

@csrf_exempt
@require_http_methods(['POST'])
def truecaller_auth(request):
    try:
        json_data = json.loads(request.body.decode(encoding='UTF-8'))
        truecaller = Truecaller.objects.get(request_id=json_data['requestId'])
        truecaller.access_token = json_data['accessToken']
        url = json_data['endpoint']
        headers = {'content-type' : 'application/json', 'Authorization' : 'Bearer {}'.format(truecaller.access_token)}
        resp = requests.get(url, headers=headers)
        if resp.ok:
            true_username = '{}{}'.format(resp.json()['name']['first'], resp.json()['name']['last'])
            user, created = User.objects.get_or_create(username=true_username)
            if created:
                user.first_name = resp.json()['name']['first']
                user.last_name = resp.json()['name']['last']
                Mentee.objects.create(user=user, phone_no=truecaller.phone_number)
            user.save()
            truecaller.user = user
            truecaller.profile_data = json.dumps(resp.json())
            truecaller.expires_at = timezone.now() + timedelta(days=90)
        truecaller.save()
        return JsonResponse({'message' : 'Success'})
    except Exception as e:
        return JsonResponse({'message' : 'Invalid request', 'status' : 'Failed'})

@require_http_methods(['GET'])
def list_mentor(request):
    mentors = Mentor.objects.all().select_related('user')
    t_posts = Post.objects.all().annotate(avg_rating=Coalesce(Avg('ratings__value'), 0.0)).order_by('-avg_rating')[:5]
    return render(request, 'mentors/list.html', {'mentors' : mentors, 'posts' : t_posts, 'section' : 'list_mentor'})

@require_http_methods(['GET', 'POST'])
def mentor_detail(request, mentor_id):
    mentor = Mentor.objects.get(id=mentor_id)
    likes = mentor.likes.all().count()
    followers = mentor.following_mentees.all().count()
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = MessageForm(request.POST)
            if form.is_valid():
                message = form.save(commit=False)
                message.user = request.user
                message.mentor = mentor
                message.save()
                messages.success(request, 'Message added successfully. Waiting for verification.')
                return redirect(reverse('core:mentor_detail', args=[mentor.id]))
        else:
            messages.error(request, 'Only Registered Users can post comments on this board. Sign up NOW')
            return redirect(reverse('core:mentor_detail', args=[mentor.id]))
    else:
        resp_form = ResponseForm()
        form = MessageForm()
    m_messages = mentor.messages.all().filter(approved=True).prefetch_related('responses').select_related('user').distinct()
    return render(request, 'mentors/detail.html', {'mentor' : mentor, 'form' : form, 'resp_form' : resp_form, 'm_messages' : m_messages, 'likes' : likes, 'followers' : followers, 'section' : 'mentor_detail'})

@require_http_methods(['POST'])
def message_response(request, message_id):
    if not request.user.is_authenticated:
        messages.error(request, 'Please Sign-in to reply!')
        return redirect('core:index')
    msg = get_object_or_404(Message, id=message_id)
    form = ResponseForm(request.POST)
    if form.is_valid():
        resp = form.save(commit=False)
        resp.message = msg
        resp.user = request.user
        resp.save()
        messages.success(request, 'Reply submitted successfully. Waiting for verification.')
        return redirect(reverse('core:mentor_detail', args=[msg.mentor.id]))
    messages.error(request, 'Error sending reply! Please try again')
    return redirect(reverse('core:mentor_detail', args=[msg.mentor.id]))

@require_http_methods(['GET'])
def list_post(request):
    posts = Post.objects.all().prefetch_related('target', 'comments', 'ratings').select_related('user').annotate(num_comments=Count('comments', distinct=True), avg_rating=Coalesce(Avg('ratings__value'), 0.0))
    category = request.GET.get('category', None)
    order_by = request.GET.get('order_by', None)
    if category:
        posts = posts.filter(category=category)
    if order_by:
        posts = posts.order_by(order_by)
    for post in posts:
        try:
            rating = post.ratings.all().get(user=request.user)
            post.rated = rating.value
        except Exception as e:
            post.rated = None
    text_form = TextForm()
    video_form = VideoForm()
    audio_form = AudioForm()
    link_form = LinkForm()
    return render(request, 'posts/list.html', {'posts' : posts, 'text_form' : text_form, 'video_form' : video_form, 'audio_form' : audio_form, 'link_form' : link_form, 'section' : 'list_post'})

@require_http_methods(['GET', 'POST'])
def post_detail(request, post_id):

core/templates/posts/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{% endblock %}
{% block content %}
{% load post %}
<script type="text/javascript" src='{% static "ckeditor/ckeditor-init.js" %}'></script>
<script type="text/javascript" src='{% static "ckeditor/ckeditor/ckeditor.js" %}'></script>
<div class="content is-full py-3 px-4 scrollbox">
    <div class="post-featured is-full">
        {% with post.target as obj %}
        {% if obj|model_name == 'text' %}
        {% if obj.thumbnail %}
        <img src="{{ obj.thumbnail.url }}">
        {% else %}
        <img src="https://cdn.pixabay.com/photo/2017/08/17/13/33/business-2651346_960_720.jpg">
        {% endif %}
        {% elif obj|model_name == 'audio' %}
        <div class="post-overlay text-center">
            <audio id="audio1" controls preload="auto">
                <source src="{{ obj.audio_file.url }}" type="audio/mpeg">
                Your browser does not support the audio tag.
            </audio>
        </div>
        {% if obj.thumbnail %}
        <img src="{{ obj.thumbnail.url }}">
        {% else %}
        <img src="https://cdn.pixabay.com/photo/2016/03/28/09/36/music-1285165_960_720.jpg">
        {% endif %}
        {% elif obj|model_name == 'video' %}
        <iframe src="{{ obj.video_url }}" frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen></iframe>
        {% elif obj|model_name == 'link' %}
        <img src="{{ obj|audio_thumbnail }}" alt="">
        {% endif %}
        {% endwith %}
    </div>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <section class="mb-3">
                <h1 class="text-black h4 mb-1">{{ post.title }}</h1>
                <ul class="list-inline mb-1">
                    <li>
                        <div class="user-avatar is-sm">
                            {% if post.get_avatar_url %}
                            <img src="{{ post.get_avatar_url }}" alt="">
                            {% else %}
                            <img src="{% static 'img/base/avatar.png' %}" alt="">
                            {% endif %}
                        </div>
                    </li>
                    <li>
                        <p class="text-gray-200 font-sm">{{ post.user.full_name }} | {{ post.created|date:"D, d M, Y | P" }}</p>
                    </li>
                    <li class="bold text-secondary"><span id="avg-rating">{% if post.avg_rating %}{{ post.avg_rating|floatformat:2 }}{% else %}0.0{% endif %}</span> <span class="text-yellow"><i class="fas fa-star"></i></span></li>
                    {% if post.target|model_name == 'link' %}
                    <li>
                        <a class="btn btn-link is-black" href="{{ post.target.content_url }}" target="_blank"><i class="fas fa-link"></i> <span class="bold text-gray-300">View Post</span></a>
                    </li>
                    {% endif %}
                </ul>
                <div class="font-md mb-2">
                    {% with post.target as obj %}
                    {% if obj|model_name == 'text' %}
                    {{ post.description }}
                    {% elif obj|model_name == 'audio' %}
                    {{ post.description }}
                    {% elif obj|model_name == 'video' %}
                    {{ post.description }}
                    {% elif obj|model_name == 'link' %}
                    {{ obj|audio_content|safe }}
                    {% endif %}
                    {% endwith %}
                </div>

                {% if request.user.is_authenticated %}
                <ul class="mt-2 list-inline mb-2">
                    <li><p class="mb-0 bold text-gray-600">Rate this post :</p></li>
                    <li>
                        <fieldset class="rating">
                            <input type="radio" id="star5" name="rating" value="5" {% if rated == 5.0 %}checked{% endif %}/><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                            <input type="radio" id="star4half" name="rating" value="4.5" {% if rated == 4.5 %}checked{% endif %}/><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
                            <input type="radio" id="star4" name="rating" value="4" {% if rated == 4.0 %}checked{% endif %}/><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
                            <input type="radio" id="star3half" name="rating" value="3.5" {% if rated == 3.5 %}checked{% endif %}/><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
                            <input type="radio" id="star3" name="rating" value="3" {% if rated == 3.0 %}checked{% endif %}/><label class = "full" for="star3" title="Meh - 3 stars"></label>
                            <input type="radio" id="star2half" name="rating" value="2.5" {% if rated == 2.5 %}checked{% endif %}/><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
                            <input type="radio" id="star2" name="rating" value="2" {% if rated == 2.0 %}checked{% endif %}/><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
                            <input type="radio" id="star1half" name="rating" value="1.5" {% if rated == 1.5 %}checked{% endif %}/><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
                            <input type="radio" id="star1" name="rating" value="1" {% if rated == 1.0 %}checked{% endif %}/><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
                            <input type="radio" id="starhalf" name="rating" value="0.5" {% if rated == 0.5 %}checked{% endif %}/><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
                        </fieldset>
                    </li>
                </ul>
                {% endif %}
            </section>

            <section class="mb-4">
                <h2 class="text-secondary mb-1">Leave a Comment</h2>
                <p class="font-sm text-gray-200 italic"><em>*Comments will be displayed once verified.</em></p>
                <form action="." method="POST">
                    <div class="mb-2">
                        {% if form.content.errors %}
                        <ul class="error-list">
                            {% for err in form.content.errors %}
                            <li>{{ err }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {{ form.content }}
                    </div>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-md">Submit</button>
                </form>
            </section>
            <section>
                <ul class="list list-comments">
                    {% for comment in comments %}
                    <li>
                        <article>
                            <ul class="list-inline">
                                <li>
                                    <div class="user-avatar is-sm">
                                        {% if comment.get_avatar_url %}
                                        <img src="{{ comment.get_avatar_url }}" alt="">
                                        {% else %}
                                        <img src="{% static 'img/base/avatar.png' %}" alt="">
                                        {% endif %}
                                    </div>
                                </li>
                                <li>
                                    <p class="text-gray-200 font-sm">{{ comment.user.full_name }} | {{ comment.created|date:"D, d M, Y | P" }}</p>
                                </li>
                            </ul>
                            <p class="mb-0">{{ comment.content|safe }}</p>
                        </article>
                    </li>
                    {% endfor %}
                </ul>
            </section>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('.rating input').change(function(e) {
            e.preventDefault();
            var in_el = $(this);
            var value = $(this).attr('value');
            $.ajax({
                url : '{% url "core:rate_post" %}',
                type : 'POST',
                data : {
                    'id' : '{{ post.id }}',
                    'value' : value
                },
                success : function(d) {
                    if (d.status == 'failed') {
                        in_el.prop('checked', false);
                        $('#inf-msg-box .alert-list').append('<li class="is-danger"><div class="alert-details"><strong>Error:</strong> '+d.message+'</div><a href="javascript:void(0)" class="alert-dismiss"><i class="fas fa-times"></i></a></li>');
                        removeInfo();
                    } else {
                        in_el.prop('checked', true);
                        $('#avg-rating').text(d.avg);
                        $('#inf-msg-box .alert-list').append('<li class="is-success"><div class="alert-details"><strong>Success:</strong> Post Rated Successfully!</div><a href="javascript:void(0)" class="alert-dismiss"><i class="fas fa-times"></i></a></li>');
                        removeInfo();
                    }
                },
                error : function(xhr, status, error) {
                    in_el.prop('checked', false);
                    $('#inf-msg-box .alert-list').append('<li class="is-danger"><div class="alert-details"><strong>Error:</strong> '+xhr['responseText']+'</div><a href="javascript:void(0)" class="alert-dismiss"><i class="fas fa-times"></i></a></li>');
                    removeInfo();
                }
            });
        });
    });
</script>
{% endblock %}