core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from core.views import *

urlpatterns = [

    # Custom admin urls
    path('su/monitor/admin/', comments_admin, name='comments_admin'),

    # Site urls
    path('', index, name='index'),
    path('account/profile/', user_profile, name='user_profile'),
    path('account/anonymous/', set_anonymous, name='set_anonymous'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('truecaller/login', truecaller_login, name='truecaller_login'),
    path('truecaller/auth', truecaller_auth, name='truecaller_auth'),
    path('mentors/', list_mentor, name='list_mentor'),
    path('mentor/<uuid:mentor_id>/', mentor_detail, name='mentor_detail'),
    path('message/respond/<uuid:message_id>/', message_response, name='message_response'),
    path('posts/', list_post, name='list_post'),
    path('posts/<uuid:post_id>/', post_detail, name='post_detail'),
    path('posts/create/', create_post, name='create_post'),
    path('posts/content/add/<uuid:post_id>/<str:ct>/', add_post_content, name='add_post_content'),
    path('posts/rate/', rate_post, name='rate_post'),
    path('mentor/follow/', follow_unfollow_mentor, name='follow_mentor'),
    path('mentor/like/', like_unlike_mentor, name='like_mentor'),
    path('streams/', live_stream, name='live_stream'),
    path('stream/message/respond/<uuid:message_id>/', stream_message_response, name='stream_message_response'),
    path('terms/', terms, name='terms'),
    path('privacy/', privacy, name='privacy'),

]

gyaanstation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from ckeditor_uploader import views as uploder_views
from core.decorators import uploader_decorator

urlpatterns = [
    path('', include(('core.urls', 'core'), namespace='core')),
    path('admin/', admin.site.urls),
    path('ckeditor/upload/', uploader_decorator(uploder_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', uploader_decorator(uploder_views.browse), name='ckeditor_browse'),
    path('oauth/', include(('social_django.urls', 'social'), namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms

from django.contrib.auth.models import User
from django.core.files import File

from core.models import (
    PostComment,
    Message,
    Response,
    Mentee,
    StreamMessage,
    StreamMsgResponse,
    Post,
    Text,
    Audio,
    Video,
    Link
)

from PIL import Image

class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ('resp_content',)

    def __init__(self, *args, **kwargs):
        super(ResponseForm, self).__init__(*args, **kwargs)
        self.fields['resp_content'].required = True

class StreamMessageForm(forms.ModelForm):
    class Meta:
        model = StreamMessage
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(StreamMessageForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class StreamMsgResponseForm(forms.ModelForm):
    class Meta:
        model = StreamMsgResponse
        fields = ('resp_content',)

    def __init__(self, *args, **kwargs):
        super(StreamMsgResponseForm, self).__init__(*args, **kwargs)
        self.fields['resp_content'].required = True

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

class MenteeForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Mentee
        fields = ('profile_pic', 'gender', 'phone_no', 'x', 'y', 'width', 'height')

    def save(self, *args, **kwargs):
        mentee = super(MenteeForm, self).save(*args, **kwargs)

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        try:
            image = Image.open(mentee.profile_pic)
            cropped_image = image.crop((x, y, w+x, h+y))
            cropped_image.save(mentee.profile_pic.path)
        except:
            pass
        return mentee

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'description')

class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ('thumbnail',)

class AudioForm(forms.ModelForm):
    class Meta:
        model = Audio
        fields = ('thumbnail', 'audio_file')

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('video_url',)

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('content_url',)

core/views.py
import json, requests

from itertools import chain
from operator import attrgetter

from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.csrf import (
    csrf_exempt,
    ensure_csrf_cookie
)
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.humanize.templatetags.humanize import intcomma
from django.contrib.contenttypes.models import ContentType

from django.http.response import (
    HttpResponse,
    JsonResponse
)
from django.contrib.auth import (
    login,
    authenticate
)

from django.conf import settings
from django.utils import timezone
from django.contrib import messages
from django.http import Http404

from django.db.models import Count, Avg
from django.db.models.functions import Coalesce

from django.contrib.auth.models import User

from core.models import *
from core.forms import *
from core.decorators import (
    ajax_required,
    mentee_required
)

# Custom Admin views here.

@staff_member_required
@require_http_methods(['GET'])
def comments_admin(request):
    comments = PostComment.objects.filter(approved=False).distinct()
    messages = Message.objects.filter(approved=False).distinct()
    responses =  Response.objects.filter(approved=False).distinct()
    monitor_objs = sorted(chain(comments, messages, responses), key=attrgetter('created'), reverse=True)
    return render(request, 'su/monitor.html', {'objs' : monitor_objs, 'section' : 'su_comments_admin'})

# Create your views here.

@ensure_csrf_cookie
def index(request):
    t_mentors = Mentor.objects.all().prefetch_related('likes').annotate(num_likes=Count('likes')).order_by('-num_likes')[:6]
    t_posts = Post.objects.all().annotate(avg_rating=Coalesce(Avg('ratings__value'), 0.0)).order_by('-avg_rating')[:20]
    return render(request, 'home/index.html', {'mentors' : t_mentors, 'posts' : t_posts, 'section' : 'index'})

@login_required
@require_http_methods(['GET', 'POST'])
def user_profile(request):
    if request.method == 'POST':
        u_form = UserForm(data=request.POST, instance=request.user)
        m_form = MenteeForm(data=request.POST, files=request.FILES, instance=request.user.mentee)
        if u_form.is_valid() and m_form.is_valid():
            user = u_form.save(commit=False)
            user.save()
            mentee = m_form.save()
            messages.success(request, 'Profile created successfully')
            return redirect('core:user_profile')
    else:
        u_form = UserForm(instance=request.user)
        if hasattr(request.user, 'mentee'):
            m_form = MenteeForm(instance=request.user.mentee)
        else:
            m_form = MenteeForm()
    try:
        dp_pic = request.user.mentee.profile_pic.url
    except:
        dp_pic = None
    anonymous = False
    if hasattr(request.user, 'mentee'):
        anonymous = request.user.mentee.anonymous
    return render(request, 'home/account/profile.html', {'pic' : dp_pic, 'u_form' : u_form, 'm_form' : m_form, 'anonymous' : anonymous, 'section' : 'profile'})

@mentee_required
@ajax_required
@require_http_methods(['POST'])
def set_anonymous(request):
    state = request.POST.get('state')
    if state == 'on':
        new_user_name = request.POST.get('username')
        user = request.user
        try:
            user.username = new_user_name
            user.save()
            mentee = user.mentee
            mentee.anonymous = True
            mentee.save()
        except:
            return JsonResponse({'status' : 'failed'})
    else:
        mentee = request.user.mentee
        mentee.anonymous = False
        mentee.save()
    return JsonResponse({'status' : 'success', 'state' : state})

@ajax_required
@require_http_methods(['POST'])
def truecaller_login(request):
    phone_num = '91{}'.format(request.POST.get('phone_number'))
    try:
        truecaller, created = Truecaller.objects.get_or_create(phone_number=phone_num)
    except Exception as e:
        return JsonResponse({'status' : 'Error', 'mesage' : str(e)})
    if created or timezone.now() >= truecaller.expires_at:
        url = 'https://api4.truecaller.com/v1/apps/requests'
        headers = {'content-type' : 'application/json', 'appKey' : settings.TRUECALLER_APP_KEY}
        data = {'phoneNumber' : phone_num}
        resp = requests.post(url, headers=headers, data=json.dumps(data))
        truecaller.expires_at = timezone.now() + timedelta(minutes=5)
        truecaller.save()
        if resp.ok:
            json_data = json.loads(resp.text)
            truecaller.request_id = json_data['requestId']
            truecaller.save()
            return JsonResponse({'status' : 'Waiting'})
    else:
        user = authenticate(request=request, phone_number=phone_num)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login Successful!')
            return JsonResponse({'status' : 'Success'})
    return JsonResponse({'status' : 'Waiting'})

@csrf_exempt
@require_http_methods(['POST'])
def truecaller_auth(request):
    try:
        json_data = json.loads(request.body.decode(encoding='UTF-8'))
        truecaller = Truecaller.objects.get(request_id=json_data['requestId'])
        truecaller.access_token = json_data['accessToken']
        url = json_data['endpoint']
        headers = {'content-type' : 'application/json', 'Authorization' : 'Bearer {}'.format(truecaller.access_token)}
        resp = requests.get(url, headers=headers)
        if resp.ok:
            true_username = '{}{}'.format(resp.json()['name']['first'], resp.json()['name']['last'])
            user, created = User.objects.get_or_create(username=true_username)
            if created:
                user.first_name = resp.json()['name']['first']
                user.last_name = resp.json()['name']['last']
                Mentee.objects.create(user=user, phone_no=truecaller.phone_number)
            user.save()
            truecaller.user = user
            truecaller.profile_data = json.dumps(resp.json())
            truecaller.expires_at = timezone.now() + timedelta(days=90)
        truecaller.save()
        return JsonResponse({'message' : 'Success'})
    except Exception as e:
        return JsonResponse({'message' : 'Invalid request', 'status' : 'Failed'})

@require_http_methods(['GET'])
def list_mentor(request):
    mentors = Mentor.objects.all().select_related('user')
    t_posts = Post.objects.all().annotate(avg_rating=Coalesce(Avg('ratings__value'), 0.0)).order_by('-avg_rating')[:5]
    return render(request, 'mentors/list.html', {'mentors' : mentors, 'posts' : t_posts, 'section' : 'list_mentor'})

@require_http_methods(['GET', 'POST'])
def mentor_detail(request, mentor_id):
    mentor = Mentor.objects.get(id=mentor_id)
    likes = mentor.likes.all().count()
    followers = mentor.following_mentees.all().count()
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = MessageForm(request.POST)
            if form.is_valid():
                message = form.save(commit=False)
                message.user = request.user
                message.mentor = mentor
                message.save()
                messages.success(request, 'Message added successfully. Waiting for verification.')
                return redirect(reverse('core:mentor_detail', args=[mentor.id]))
        else:
            messages.error(request, 'Only Registered Users can post comments on this board. Sign up NOW')
            return redirect(reverse('core:mentor_detail', args=[mentor.id]))
    else:
        resp_form = ResponseForm()
        form = MessageForm()
    m_messages = mentor.messages.all().filter(approved=True).prefetch_related('responses').select_related('user').distinct()
    return render(request, 'mentors/detail.html', {'mentor' : mentor, 'form' : form, 'resp_form' : resp_form, 'm_messages' : m_messages, 'likes' : likes, 'followers' : followers, 'section' : 'mentor_detail'})

@require_http_methods(['POST'])
def message_response(request, message_id):
    if not request.user.is_authenticated:
        messages.error(request, 'Please Sign-in to reply!')
        return redirect('core:index')
    msg = get_object_or_404(Message, id=message_id)
    form = ResponseForm(request.POST)
    if form.is_valid():
        resp = form.save(commit=False)
        resp.message = msg
        resp.user = request.user
        resp.save()
        messages.success(request, 'Reply submitted successfully. Waiting for verification.')
        return redirect(reverse('core:mentor_detail', args=[msg.mentor.id]))
    messages.error(request, 'Error sending reply! Please try again')
    return redirect(reverse('core:mentor_detail', args=[msg.mentor.id]))

@require_http_methods(['GET'])
def list_post(request):
    posts = Post.objects.all().prefetch_related('target', 'comments', 'ratings').select_related('user').annotate(num_comments=Count('comments', distinct=True), avg_rating=Coalesce(Avg('ratings__value'), 0.0))
    category = request.GET.get('category', None)
    order_by = request.GET.get('order_by', None)
    if category:
        posts = posts.filter(category=category)
    if order_by:
        posts = posts.order_by(order_by)
    for post in posts:
        try:
            rating = post.ratings.all().get(user=request.user)
            post.rated = rating.value
        except Exception as e:
            post.rated = None
    text_form = TextForm()
    video_form = VideoForm()
    audio_form = AudioForm()
    link_form = LinkForm()
    return render(request, 'posts/list.html', {'posts' : posts, 'text_form' : text_form, 'video_form' : video_form, 'audio_form' : audio_form, 'link_form' : link_form, 'section' : 'list_post'})

@require_http_methods(['GET', 'POST'])
def post_detail(request, post_id):

core/templates/mentors/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load mentor %}
{% block title %}{% endblock %}
{% block content %}
<script type="text/javascript" src='{% static "ckeditor/ckeditor-init.js" %}'></script>
<script type="text/javascript" src='{% static "ckeditor/ckeditor/ckeditor.js" %}'></script>
<div class="content is-full py-3 px-4 scrollbox">
    <div class="row">
        <div class="col-md-3 mb-xs-3 divider-rt">
            <div class="mb-3">
                <div class="user-avatar is-lg mb-2">
                    {% if mentor.profile_pic %}
                    <img src="{{mentor.profile_pic.url}}" alt="">
                    {% else %}
                    <img src="{% static 'img/base/avatar.png' %}" alt="">
                    {% endif %}
                </div>
                <div class="user-details">
                    <h2 class="normal text-secondary">{{ mentor.user.full_name }}</h2>
                    <p class="text-gray-400 bold mb-1">Information Technology</p>
                    {% if request.user.is_authenticated and request.user|is_mentee %}
                    <div class="mb-2">
                        <a href="javascript:void(0)" class="btn btn-rounded btn-primary bold" id="follow-btn" data-id="{{ mentor.id }}" data-num="{{ followers }}">{% if mentor not in request.user.mentee.following.all %}Follow{% else %}Unfollow{% endif %}</a>
                        <a href="javascript:void(0)" class="btn btn-rounded btn-secondary bold" id="like-btn" data-id="{{ mentor.id }}" data-num="{{ likes }}">{% if request.user not in mentor.likes.all %}Like{% else %}Unlike{% endif %}</a>
                    </div>
                    {% endif %}
                    <ul class="list-inline">
                        <li>
                            <p class="text-gray-600 h5 mb-0 bold" id="followers-count">{{ followers|convert_int }}</p>
                            <p class="text-gray-200 font-sm">Followers</p>
                        </li>
                        <li>
                            <p class="text-gray-600 h5 mb-0 bold" id="likes-count">{{ likes|convert_int }}</p>
                            <p class="text-gray-200 font-sm">Likes</p>
                        </li>
                    </ul>
                </div>
            </div>
            <h2 class="text-secondary mb-2">Biography</h2>
            {{ mentor.bio|safe }}
        </div>
        <div class="col-md-9">
            <section class="scrollbox mb-4" style="max-height: 46vh">
                <h2 class="text-secondary mb-1">Message Board</h2>
                <ul class="list list-comments">
                    {% for message in m_messages %}
                    <li>
                        <article>
                            <ul class="list-inline">
                                <li>
                                    <div class="user-avatar is-sm">
                                        {% if message.get_avatar_url %}
                                        <img src="{{ message.get_avatar_url }}" alt="">
                                        {% else %}
                                        <img src="{% static 'img/base/avatar.png' %}" alt="">
                                        {% endif %}
                                    </div>
                                </li>
                                <li>
                                    <p class="text-gray-200 font-sm">{{ message.user.full_name }} | {{ message.created|date:"D, d M, Y | P" }}</p>
                                </li>
                            </ul>

                            <div class="d-flex align-items-center justify-content-between">
                                <div class="comment-para" style="margin-left: 40px;">
                                    {{ message.content|safe }}
                                </div>
                                <div class="flex-shrink-0">
                                    <a href="#" class="btn bold is-primary btn-link reply-btn" data-id="{{ message.id }}">Reply</a>
                                </div>
                            </div>
                        </article>
                        {% with message|approved_responses as responses %}
                        {% if responses|length > 0 %}
                        <ul class="list">
                            {% for response in responses  %}
                            <li>
                                <ul class="list-inline">
                                    <li>
                                        <div class="user-avatar is-sm">
                                            {% if response.get_avatar_url %}
                                            <img src="{{ response.get_avatar_url }}" alt="">
                                            {% else %}
                                            <img src="{% static 'img/base/avatar.png' %}" alt="">
                                            {% endif %}
                                        </div>
                                    </li>
                                    <li>
                                        <p class="text-gray-200 font-sm">{{ response.user.full_name }} | {{ response.created|date:"D, d M, Y | P" }}</p>
                                    </li>
                                </ul>
                                <div class="comment-para" style="margin-left: 40px;">
                                    {{ response.resp_content|safe }}
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {% endwith %}
                    </li>
                    {% endfor %}
                </ul>
            </section>
            <section>
                <form action="." method="POST">
                    <p class="font-sm text-gray-200 italic"><em>*Messages will be displayed once verified.</em></p>
                    <div class="mb-2">
                        {% if form.content.errors %}
                        <ul class="error-list">
                            {% for err in form.content.errors %}
                            <li>{{ err }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {{ form.content }}
                    </div>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-md">Submit</button>
                </form>
            </section>
        </div>
    </div>
</div>

<div class="modal fade" id="reply-modal" tabindex="-1" role="dialog" aria-labelledby="addPostLabel" aria-hidden="true" data-auth="{{ request.user.is_authenticated }}">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="text-right">
                <button type="button" class="close btn btn-link h4" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body pb-4 pt-2 px-4">
                <h2 class="mb-1">Send Reply</h2>
                <form method="POST" id="reply-form">
                    {{ resp_form.resp_content }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary js-crop-and-upload mt-2">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#follow-btn').click(function(e) {
            e.preventDefault();
            var m_id = $(this).data('id');
            var num = $(this).data('num');
            $.ajax({
                url : '{% url "core:follow_mentor" %}',
                type : 'POST',
                data : {
                    'id' : m_id
                },
                success : function(d) {
                    if (d.status == 'success') {
                        $('#followers-count').text(d.followers);
                        if ($('#follow-btn').text() === 'Follow') {
                            $('#follow-btn').text('Unfollow');
                        } else {
                            $('#follow-btn').text('Follow');
                        }
                    } else{
                        console.log(d.message)
                    }
                },
                error : function(xhr, status, error) {
                    console.log(error);
                }
            });
        });

        $('#like-btn').click(function(e) {
            e.preventDefault();
            var m_id = $(this).data('id');
            var num = $(this).data('num');
            $.ajax({
                url : '{% url "core:like_mentor" %}',
                type : 'POST',
                data : {
                    'id' : m_id
                },
                success : function(d) {
                    if (d.status == 'success') {
                        $('#likes-count').text(d.likes);
                        if ($('#like-btn').text() === 'Like') {
                            $('#like-btn').text('Unlike');
                        } else {
                            $('#like-btn').text('Like');
                        }
                    } else{
                        $('#inf-msg-box .alert-list').append('<li class="is-danger"><div class="alert-details"><strong>Error:</strong> '+d.message+'</div><a href="javascript:void(0)" class="alert-dismiss"><i class="fas fa-times"></i></a></li>');
                        removeInfo();
                    }
                },
                error : function(xhr, status, error) {
                    $('#inf-msg-box .alert-list').append('<li class="is-danger"><div class="alert-details"><strong>Error:</strong> '+xhr['responseText']+'</div><a href="javascript:void(0)" class="alert-dismiss"><i class="fas fa-times"></i></a></li>');
                    removeInfo();
                }
            });
        });

        $('.reply-btn').click(function() {
            var auth = $('#reply-modal').attr('data-auth');
            if (auth == 'False') {
                $('#inf-msg-box .alert-list').append('<li class="is-danger"><div class="alert-details"><strong>Error:</strong> Please sign-in to reply!</div><a href="javascript:void(0)" class="alert-dismiss"><i class="fas fa-times"></i></a></li>');
                removeInfo();
                return;
            }
            var msg_id = $(this).attr('data-id');
            $('#reply-form').attr('action', '/message/respond/'+ msg_id +'/');
            $('#reply-modal').modal('show');
        });
    });
</script>
{% endblock %}

core/templates/mentors/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{% endblock %}
{% block content %}
<div class="content py-3 px-4 scrollbox">
    <section class="mb-4">
        <ul class="list-mentors">
            {% for mentor in mentors %}
            <li class="br-15 shadow-1 bg-white text-center">
                <a href="{{ mentor.get_absolute_url }}">
                    <div class="p-2 border-bottom border-light">
                        <div class="user-avatar d-centered mb-1">
                            {% if mentor.profile_pic %}
                            <img src="{{mentor.profile_pic.url}}" alt="">
                            {% else %}
                            <img src="{% static 'img/base/avatar.png' %}" alt="">
                            {% endif %}
                        </div>
                        <h4 class="text-secondary">{{ mentor.user.first_name }} {{ mentor.user.last_name }}</h4>
                        <p class="text-gray-200">{{ mentor.industry }}</p>
                        <p class="text-primary bold">{{ mentor.designation }}</p>
                    </div>
                    <div class="p-2">
                        <div class="text-truncate">{{ mentor.bio|safe }}</div>
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
    </section>
</div>
<div class="sidebar is-rt">
    <div class="p-2">
        <h3 class="title">Top Posts</h3>
        <div class="scrollbox">
            <ul class="list list-lg">
                {% for post in posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">
                        <div class="br-15 shadow-1 bg-white p-2">
                            <h4 class="text-gray-400">{{ post.title }}</h4>
                            <p class="text-gray-100 semibold mb-2">{{ post.user.full_name }} - {{ post.created|date:"d-m-Y" }}</p>
                            <p class="article-meta">{{ post.description|safe }}</p>
                        </div>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}