core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from core.views import *

urlpatterns = [

    # Custom admin urls
    path('su/monitor/admin/', comments_admin, name='comments_admin'),

    # Site urls
    path('', index, name='index'),
    path('account/profile/', user_profile, name='user_profile'),
    path('account/anonymous/', set_anonymous, name='set_anonymous'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('truecaller/login', truecaller_login, name='truecaller_login'),
    path('truecaller/auth', truecaller_auth, name='truecaller_auth'),
    path('mentors/', list_mentor, name='list_mentor'),
    path('mentor/<uuid:mentor_id>/', mentor_detail, name='mentor_detail'),
    path('message/respond/<uuid:message_id>/', message_response, name='message_response'),
    path('posts/', list_post, name='list_post'),
    path('posts/<uuid:post_id>/', post_detail, name='post_detail'),
    path('posts/create/', create_post, name='create_post'),
    path('posts/content/add/<uuid:post_id>/<str:ct>/', add_post_content, name='add_post_content'),
    path('posts/rate/', rate_post, name='rate_post'),
    path('mentor/follow/', follow_unfollow_mentor, name='follow_mentor'),
    path('mentor/like/', like_unlike_mentor, name='like_mentor'),
    path('streams/', live_stream, name='live_stream'),
    path('stream/message/respond/<uuid:message_id>/', stream_message_response, name='stream_message_response'),
    path('terms/', terms, name='terms'),
    path('privacy/', privacy, name='privacy'),

]

gyaanstation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from ckeditor_uploader import views as uploder_views
from core.decorators import uploader_decorator

urlpatterns = [
    path('', include(('core.urls', 'core'), namespace='core')),
    path('admin/', admin.site.urls),
    path('ckeditor/upload/', uploader_decorator(uploder_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', uploader_decorator(uploder_views.browse), name='ckeditor_browse'),
    path('oauth/', include(('social_django.urls', 'social'), namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms

from django.contrib.auth.models import User
from django.core.files import File

from core.models import (
    PostComment,
    Message,
    Response,
    Mentee,
    StreamMessage,
    StreamMsgResponse,
    Post,
    Text,
    Audio,
    Video,
    Link
)

from PIL import Image

class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ('resp_content',)

    def __init__(self, *args, **kwargs):
        super(ResponseForm, self).__init__(*args, **kwargs)
        self.fields['resp_content'].required = True

class StreamMessageForm(forms.ModelForm):
    class Meta:
        model = StreamMessage
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(StreamMessageForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

class StreamMsgResponseForm(forms.ModelForm):
    class Meta:
        model = StreamMsgResponse
        fields = ('resp_content',)

    def __init__(self, *args, **kwargs):
        super(StreamMsgResponseForm, self).__init__(*args, **kwargs)
        self.fields['resp_content'].required = True

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

class MenteeForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Mentee
        fields = ('profile_pic', 'gender', 'phone_no', 'x', 'y', 'width', 'height')

    def save(self, *args, **kwargs):
        mentee = super(MenteeForm, self).save(*args, **kwargs)

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        try:
            image = Image.open(mentee.profile_pic)
            cropped_image = image.crop((x, y, w+x, h+y))
            cropped_image.save(mentee.profile_pic.path)
        except:
            pass
        return mentee

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'description')

class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ('thumbnail',)

class AudioForm(forms.ModelForm):
    class Meta:
        model = Audio
        fields = ('thumbnail', 'audio_file')

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('video_url',)

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('content_url',)

core/views.py
import json, requests

from itertools import chain
from operator import attrgetter

from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.csrf import (
    csrf_exempt,
    ensure_csrf_cookie
)
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.humanize.templatetags.humanize import intcomma
from django.contrib.contenttypes.models import ContentType

from django.http.response import (
    HttpResponse,
    JsonResponse
)
from django.contrib.auth import (
    login,
    authenticate
)

from django.conf import settings
from django.utils import timezone
from django.contrib import messages
from django.http import Http404

from django.db.models import Count, Avg
from django.db.models.functions import Coalesce

from django.contrib.auth.models import User

from core.models import *
from core.forms import *
from core.decorators import (
    ajax_required,
    mentee_required
)

# Custom Admin views here.

@staff_member_required
@require_http_methods(['GET'])
def comments_admin(request):
    comments = PostComment.objects.filter(approved=False).distinct()
    messages = Message.objects.filter(approved=False).distinct()
    responses =  Response.objects.filter(approved=False).distinct()
    monitor_objs = sorted(chain(comments, messages, responses), key=attrgetter('created'), reverse=True)
    return render(request, 'su/monitor.html', {'objs' : monitor_objs, 'section' : 'su_comments_admin'})

# Create your views here.

@ensure_csrf_cookie
def index(request):
    t_mentors = Mentor.objects.all().prefetch_related('likes').annotate(num_likes=Count('likes')).order_by('-num_likes')[:6]
    t_posts = Post.objects.all().annotate(avg_rating=Coalesce(Avg('ratings__value'), 0.0)).order_by('-avg_rating')[:20]
    return render(request, 'home/index.html', {'mentors' : t_mentors, 'posts' : t_posts, 'section' : 'index'})

@login_required
@require_http_methods(['GET', 'POST'])
def user_profile(request):
    if request.method == 'POST':
        u_form = UserForm(data=request.POST, instance=request.user)
        m_form = MenteeForm(data=request.POST, files=request.FILES, instance=request.user.mentee)
        if u_form.is_valid() and m_form.is_valid():
            user = u_form.save(commit=False)
            user.save()
            mentee = m_form.save()
            messages.success(request, 'Profile created successfully')
            return redirect('core:user_profile')
    else:
        u_form = UserForm(instance=request.user)
        if hasattr(request.user, 'mentee'):
            m_form = MenteeForm(instance=request.user.mentee)
        else:
            m_form = MenteeForm()
    try:
        dp_pic = request.user.mentee.profile_pic.url
    except:
        dp_pic = None
    anonymous = False
    if hasattr(request.user, 'mentee'):
        anonymous = request.user.mentee.anonymous
    return render(request, 'home/account/profile.html', {'pic' : dp_pic, 'u_form' : u_form, 'm_form' : m_form, 'anonymous' : anonymous, 'section' : 'profile'})

@mentee_required
@ajax_required
@require_http_methods(['POST'])
def set_anonymous(request):
    state = request.POST.get('state')
    if state == 'on':
        new_user_name = request.POST.get('username')
        user = request.user
        try:
            user.username = new_user_name
            user.save()
            mentee = user.mentee
            mentee.anonymous = True
            mentee.save()
        except:
            return JsonResponse({'status' : 'failed'})
    else:
        mentee = request.user.mentee
        mentee.anonymous = False
        mentee.save()
    return JsonResponse({'status' : 'success', 'state' : state})

@ajax_required
@require_http_methods(['POST'])
def truecaller_login(request):
    phone_num = '91{}'.format(request.POST.get('phone_number'))
    try:
        truecaller, created = Truecaller.objects.get_or_create(phone_number=phone_num)
    except Exception as e:
        return JsonResponse({'status' : 'Error', 'mesage' : str(e)})
    if created or timezone.now() >= truecaller.expires_at:
        url = 'https://api4.truecaller.com/v1/apps/requests'
        headers = {'content-type' : 'application/json', 'appKey' : settings.TRUECALLER_APP_KEY}
        data = {'phoneNumber' : phone_num}
        resp = requests.post(url, headers=headers, data=json.dumps(data))
        truecaller.expires_at = timezone.now() + timedelta(minutes=5)
        truecaller.save()
        if resp.ok:
            json_data = json.loads(resp.text)
            truecaller.request_id = json_data['requestId']
            truecaller.save()
            return JsonResponse({'status' : 'Waiting'})
    else:
        user = authenticate(request=request, phone_number=phone_num)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login Successful!')
            return JsonResponse({'status' : 'Success'})
    return JsonResponse({'status' : 'Waiting'})

@csrf_exempt
@require_http_methods(['POST'])
def truecaller_auth(request):
    try:
        json_data = json.loads(request.body.decode(encoding='UTF-8'))
        truecaller = Truecaller.objects.get(request_id=json_data['requestId'])
        truecaller.access_token = json_data['accessToken']
        url = json_data['endpoint']
        headers = {'content-type' : 'application/json', 'Authorization' : 'Bearer {}'.format(truecaller.access_token)}
        resp = requests.get(url, headers=headers)
        if resp.ok:
            true_username = '{}{}'.format(resp.json()['name']['first'], resp.json()['name']['last'])
            user, created = User.objects.get_or_create(username=true_username)
            if created:
                user.first_name = resp.json()['name']['first']
                user.last_name = resp.json()['name']['last']
                Mentee.objects.create(user=user, phone_no=truecaller.phone_number)
            user.save()
            truecaller.user = user
            truecaller.profile_data = json.dumps(resp.json())
            truecaller.expires_at = timezone.now() + timedelta(days=90)
        truecaller.save()
        return JsonResponse({'message' : 'Success'})
    except Exception as e:
        return JsonResponse({'message' : 'Invalid request', 'status' : 'Failed'})

@require_http_methods(['GET'])
def list_mentor(request):
    mentors = Mentor.objects.all().select_related('user')
    t_posts = Post.objects.all().annotate(avg_rating=Coalesce(Avg('ratings__value'), 0.0)).order_by('-avg_rating')[:5]
    return render(request, 'mentors/list.html', {'mentors' : mentors, 'posts' : t_posts, 'section' : 'list_mentor'})

@require_http_methods(['GET', 'POST'])
def mentor_detail(request, mentor_id):
    mentor = Mentor.objects.get(id=mentor_id)
    likes = mentor.likes.all().count()
    followers = mentor.following_mentees.all().count()
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = MessageForm(request.POST)
            if form.is_valid():
                message = form.save(commit=False)
                message.user = request.user
                message.mentor = mentor
                message.save()
                messages.success(request, 'Message added successfully. Waiting for verification.')
                return redirect(reverse('core:mentor_detail', args=[mentor.id]))
        else:
            messages.error(request, 'Only Registered Users can post comments on this board. Sign up NOW')
            return redirect(reverse('core:mentor_detail', args=[mentor.id]))
    else:
        resp_form = ResponseForm()
        form = MessageForm()
    m_messages = mentor.messages.all().filter(approved=True).prefetch_related('responses').select_related('user').distinct()
    return render(request, 'mentors/detail.html', {'mentor' : mentor, 'form' : form, 'resp_form' : resp_form, 'm_messages' : m_messages, 'likes' : likes, 'followers' : followers, 'section' : 'mentor_detail'})

@require_http_methods(['POST'])
def message_response(request, message_id):
    if not request.user.is_authenticated:
        messages.error(request, 'Please Sign-in to reply!')
        return redirect('core:index')
    msg = get_object_or_404(Message, id=message_id)
    form = ResponseForm(request.POST)
    if form.is_valid():
        resp = form.save(commit=False)
        resp.message = msg
        resp.user = request.user
        resp.save()
        messages.success(request, 'Reply submitted successfully. Waiting for verification.')
        return redirect(reverse('core:mentor_detail', args=[msg.mentor.id]))
    messages.error(request, 'Error sending reply! Please try again')
    return redirect(reverse('core:mentor_detail', args=[msg.mentor.id]))

@require_http_methods(['GET'])
def list_post(request):
    posts = Post.objects.all().prefetch_related('target', 'comments', 'ratings').select_related('user').annotate(num_comments=Count('comments', distinct=True), avg_rating=Coalesce(Avg('ratings__value'), 0.0))
    category = request.GET.get('category', None)
    order_by = request.GET.get('order_by', None)
    if category:
        posts = posts.filter(category=category)
    if order_by:
        posts = posts.order_by(order_by)
    for post in posts:
        try:
            rating = post.ratings.all().get(user=request.user)
            post.rated = rating.value
        except Exception as e:
            post.rated = None
    text_form = TextForm()
    video_form = VideoForm()
    audio_form = AudioForm()
    link_form = LinkForm()
    return render(request, 'posts/list.html', {'posts' : posts, 'text_form' : text_form, 'video_form' : video_form, 'audio_form' : audio_form, 'link_form' : link_form, 'section' : 'list_post'})

@require_http_methods(['GET', 'POST'])
def post_detail(request, post_id):

core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/static/img/base/favicon.png" type="image/x-icon">
    <link rel="icon" href="/static/img/base/favicon.png" type="image/x-icon">

    <!-- Font Families -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <!-- Global Stylesheet -->
    <link rel="stylesheet" href="/static/css/main.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
</head>

<body>
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <main class="wrapper">
        <div class="wrapper-inner">
            <div class="sidebar is-lt">
                <div class="sidebar__header">
                    <a href="/" class="sidebar__logo d-block">
                        <img src="/static/img/base/logo.png" alt="">
                    </a>
                </div>
                <div class="sidebar__body p-1">
                    <div class="sidebar__vd mb-4 br-08">
                        <!-- Video Here -->
                    </div>
                    <div class="vd__time">
                        <h2>Sun 12:30 PM</h2>
                    </div>
                    <div class="vd__topic mt-2">
                        <h3 class="text-primary">Stay Tuned for Live Gyaan Session</h3>
                    </div>
                </div>
                <div class="sidebar__footer bg-primary py-1">
                    <ul class="list-inline is-bordered">
                        <li><a href="{% url 'core:privacy' %}">Privacy Policy</a></li>
                        <li><a href="{% url 'core:terms' %}">Terms</a></li>
                    </ul>
                </div>
            </div>

            <div class="main-content">
                <header class="header">
                    <div class="header__sm">
                        <a href="/">
                            <img src="/static/img/base/logo-dark.png" alt="">
                        </a>
                    </div>
                    <ul class="list-inline nav nav__lt">
                        <li><a href="{% url 'core:list_mentor' %}" class="{% if 'mentor' in section %}active{% endif %}">Gyaan Guru</a></li>
                        <li><a href="{% url 'core:live_stream' %}" class="{% if 'stream' in section %}active{% endif %}">Gyaan Live</a></li>
                        <li><a href="{% url 'core:list_post' %}" class="{% if 'post' in section %}active{% endif %}">Gyaan Dunia</a></li>
                    </ul>
                    <ul class="list-inline nav nav__rt">
                        {% if section != 'index' and not user.is_authenticated %}
                        <li class="login__btn">
                            <a href="{% url 'core:index' %}" class="btn btn-primary btn-outline">Login</a>
                        </li>
                        {% endif %}
                        {% if not user.is_authenticated %}
                        <li class="header__sm-btn">
                            <a href="javascript:void(0)" data-toggle="modal" data-target="#exampleModal"
                                class="btn btn-primary btn-outline">Login</a>
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li>
                            <div class="user-dropdown user">
                                <div class="user-avatar is-sm">
                                    {% if user.mentee.profile_pic %}
                                    <img src="{{ user.mentee.profile_pic.url }}"
                                        alt="">
                                    {% else %}
                                    <img src="{% static 'img/base/avatar.png' %}"
                                        alt="">
                                    {% endif %}
                                </div>
                                <a href="javascript:void(0)" class="align-items-start d-flex"><span class="mr-1">{{ user.first_name }} {{ user.last_name }}</span> <i class="fas fa-sort-down"></i></a>
                                <ul class="user-dropdown-sub">
                                    <li class="user p-1 bg-primary text-white">
                                        <div class="user-avatar is-sm">
                                            {% if user.mentee.profile_pic %}
                                            <img src="{{ user.mentee.profile_pic.url }}"
                                                alt="">
                                            {% else %}
                                            <img src="{% static 'img/base/avatar.png' %}"
                                                alt="">
                                            {% endif %}
                                        </div>
                                        <div class="user-details">
                                            <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                                        </div>
                                    </li>
                                    <li class="p-1">
                                        <ul class="list">
                                            <li><a href="{% url 'core:user_profile' %}"><i class="fas fa-user mr-1"></i> Account Profile</a></li>
                                            <li><a href="{% url 'core:logout' %}"><i class="fas fa-sign-out-alt mr-1"></i> Log Out</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        {% endif %}
                    </ul>
                </header>
                {% block content %}{% endblock %}
            </div>
        </div>

        <div id="inf-msg-box">
            <ul class="alert-list">
                {% if messages %}
                {% for message in messages %}
                {% if message.tags == "error" %}
                <li class="is-danger">
                    <div class="alert-details">
                        <strong>Error:</strong> {{ message|safe }}
                    </div>
                    <a href="javascript:void(0)" class="alert-dismiss"><i class="fas fa-times"></i></a>
                </li>
                {% else %}
                <li class="is-success">
                    <div class="alert-details">
                        <strong>Success:</strong> {{ message|safe }}
                    </div>
                    <a href="javascript:void(0)" class="alert-dismiss"><i class="fas fa-times"></i></a>
                </li>
                {% endif %}
                {% endfor %}
                {% endif %}
            </ul>
        </div>
    </main>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-body p-4">
                    <div class="account-wrapper">
                        <div class="text-right">
                            <button type="button" class="btn btn-link h3" data-dismiss="modal">×</button>
                        </div>
                        <div class="mb-2">
                            <h2 class="bold h4 text-secondary">Welcome Back!</h2>
                            <p class="text-gray-200 font-lg">Login to your account</p>
                        </div>

                        <div class="mb-1">
                            <a href="{% url 'social:begin' 'facebook' %}" class="btn bg-facebook btn-block btn-icon">
                                <div class="btn-icon-in"><i class="fab fa-facebook-f"></i></div>
                                <span class="btn-text">Login with Facebook</span>
                            </a>
                        </div>

                        <div class="mb-1">
                            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn bg-google btn-block btn-icon">
                                <div class="btn-icon-in"><i class="fab fa-google"></i></div>
                                <span class="btn-text">Login with Google</span>
                            </a>
                        </div>

                        <div class="mb-1 popup-container">
                            <button class="btn bg-truecaller btn-block btn-icon" data-toggle="popup"
                                data-target="#m-truecaller">
                                <div class="btn-icon-in icon-truecaller"><i class="fas fa-phone"></i></div>
                                <span class="btn-text">Login with Truecaller</span>
                            </button>
                            <div class="popup" id="m-truecaller">
                                <div class="fieldset bg-white">
                                    <form action="" id="m-true-form">
                                        <div class="mb-2">
                                            <div class="input-group">
                                                <div class="icon-truecaller input-icon">
                                                    <i class="fas fa-phone text-truecaller"></i>
                                                </div>
                                                <div class="input-text md-form">
                                                    <input type="tel" class="form-control" maxlength="10"
                                                        placeholder="Your truecaller number" id="m-true-num">
                                                    <label for="">Number</label>
                                                </div>
                                            </div>
                                        </div>
                                        <button id="m-true-login-btn" type="submit" class="btn btn-primary">Submit</button>
                                    </form>
                                    <div class="text-center" style="display: none;" id="m-true-loader">
                                        <img src="/static/img/base/loader.gif" class="d-block d-centered img-responsive" alt="">
                                        <p class="font-sm" id="m-true-msg">Please wait, or grant the permission on your mobile application to login</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#m-true-form').submit(function(e){
                e.preventDefault();
                $('#m-true-form').hide();
                $('#m-true-loader').show();
                function asyncLogin() {
                    $.ajax({
                        url : '{% url "core:truecaller_login" %}',
                        type : 'POST',
                        data : {
                            'phone_number' : $('#m-true-num').val()
                        },
                        success : function(d){
                            if (d.status === 'Success') {
                                $('#m-true-msg').text('Permission granted, Login Successful!');
                                clearInterval(intervalLogin);
                                location.reload();
                            }
                        }
                    });
                }
                var intervalLogin = setInterval(asyncLogin, 5000);
            });

            $('.alert-list').on('click', '.alert-dismiss', function(e) {
                e.preventDefault();
                $(this).parent().remove();
            });

        });
        function removeInfo() {
            $('.alert-list > li').each(function(i){
                if ( i === 0) {
                    $(this).delay(2000).fadeOut('slow', function(){
                        $(this).remove();
                    });
                }
                $(this).delay(i * 4000).fadeOut('slow', function(){
                    $(this).remove();
                });
            })
        }
    </script>

    <!-- Global Scripts -->
    <script src="/static/js/script.js"></script>
    <script type="text/javascript">
		function csrfSafeMethod(e){return/^(GET|HEAD|OPTIONS|TRACE)$/.test(e)}var csrftoken=Cookies.get('csrftoken');$.ajaxSetup({beforeSend:function(e,t){csrfSafeMethod(t.type)||this.crossDomain||e.setRequestHeader("X-CSRFToken",csrftoken)}});
	</script>
</body>

</html>

core/templates/terms.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Gyaanstation | Terms & Conditions{% endblock %}
{% block content %}
<div class="content is-full py-3 px-4 scrollbox">
    <section class="mb-4">
        <h2 class="text-secondary mb-1">Terms and Conditions</h2>
        <!-- Terms here -->
    </section>
</div>
{% endblock %}